
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('user').del()
    .then(function () {
      // Inserts seed entries
      return knex('user').insert([
        { first_name: 'Stan', last_name: 'Marsh', img_url: 'http://vignette2.wikia.nocookie.net/southpark/images/a/a7/StanMarsh.png/revision/latest?cb=20160918033335', phone_number: '2104238354', company_name: 'This name', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', email: 'bob@bobert.com', venue_owner: true, event_planner: true},
        { first_name: 'Eric', last_name: 'Cartmen', img_url: 'https://upload.wikimedia.org/wikipedia/en/7/77/EricCartman.png', phone_number: '2945550392', company_name: 'Casa bonita', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat', email: 'bobert@bobert.com', venue_owner: false, event_planner: true },
        { first_name: 'Kyle', last_name: 'Broflovski', img_url: 'http://images2.fanpop.com/images/photos/6400000/kyle-is-cute-kyle-broflovski-6444563-400-300.gif', phone_number: '2395550392', company_name: 'Kyle enterprises', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit', email: 'kyle@bobert.com', venue_owner: true, event_planner: false },
        { first_name: 'Kenny', last_name: 'McCormick', img_url: 'http://orig13.deviantart.net/c2bf/f/2014/324/8/e/beat_up_kenny_render_by_slenderman2301-d87358b.png', phone_number: '3035553948', company_name: 'Kenny Inc.', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id', email: 'Kenny@Kennyyyyyy.com', venue_owner: false, event_planner: true },
        { first_name: 'Randy', last_name: 'Marsh', img_url: 'https://chasingthedionysian.files.wordpress.com/2015/09/2614857-7410027542-randy.jpg', phone_number: '3035559483', company_name: 'Randy\'s Sex Dungeon', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', email: 'bob@bobert.com', venue_owner: true, event_planner: false },
        { first_name: 'Wendy', last_name: 'Testaburger', img_url: 'http://southparkstudios.mtvnimages.com/shared/characters/kids/wendy-testaburger.jpg', phone_number: '2945559438', company_name: 'Wendys', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', email: 'bob@bobert.com', venue_owner: true  , event_planner: true },
      ]);
    });
};
