
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('venue').del()
    .then(function () {
      // Inserts seed entries
      return knex('venue').insert([
        { address: '123 fake St', city: 'Denver', state: 'Colorado', zip_code: 80203, name: 'Burger Town', email: 'burger@burgertown.com', phone: '3035559283', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', img_url: 'http://esq.h-cdn.co/assets/cm/15/06/54d3cdbba4f40_-_esq-01-bar-lgn.jpg', user_id: 2 },
        { address: '783 fake St', city: 'Colorado Springs', state: 'Colorado', zip_code: 80399, name: 'lightly Fried Fish Fillets', email: 'fish@fishfillets.com', phone: '3035551323', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', img_url: 'http://www.buddhabar.com/img/carousel/Slides/Restaurants/Manille/1.jpg', user_id: 4 },
        { address: '23894 fake St', city: 'Bolder', state: 'Colorado', zip_code: 83329, name: 'El Pollo Diablo', email: 'Pollo@pollodiablo.com', phone: '3335552342', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', img_url: 'http://www.algonquinhotel.com/wp-content/uploads/2015/02/stories-blue-bar.jpg', user_id: 4 },
        { address: '23 fake St', city: 'Bolder', state: 'Colorado', zip_code: 83329, name: 'Terrible Italian Food', email: 'Terrible@theworst.com', phone: '2015552341', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.', img_url: 'http://ww3.hdnux.com/photos/53/52/37/11446250/5/920x1240.jpg', user_id: 1 },
        { address: '23 fake St', city: 'Bolder', state: 'Colorado', zip_code: 83329, name: 'Terrible Italian Food', email: 'Terrible@theworst.com', phone: '2015552341', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.', img_url: 'http://ww3.hdnux.com/photos/53/52/37/11446250/5/920x1240.jpg', user_id: 1 },
        { address: '23233 fake St', city: 'Denver', state: 'Colorado', zip_code: 18394, name: 'Is It Chicken', email: 'Chicken@Chickenene.com', phone: '2015553928', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipisicing elit.', img_url: 'http://www.secondcity.com/wp-content/uploads/2016/03/TimothyMSchmidt-4799_sized.jpg', user_id: 5 },
        { address: '777 fake St', city: 'Denver', state: 'Colorado', zip_code: 39402, name: 'Meat and Stuff', email: 'Meat@meatstuff.com', phone: '2105550928', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipisicing elit.', img_url: 'http://www.secondcity.com/wp-content/uploads/2016/03/TimothyMSchmidt-4799_sized.jpg', user_id: 6 },
      ]);
    });
};
